select * from state;

insert into state (name, country_id) values ('Alabama', 2);
insert into state (name, country_id) values ('Alaska', 2);
insert into state (name, country_id) values ('Arizona', 2);
insert into state (name, country_id) values ('Arkansas', 2);
insert into state (name, country_id) values ('California', 2);
insert into state (name, country_id) values ('Colorado', 2);
insert into state (name, country_id) values ('Connecticut', 2);
insert into state (name, country_id) values ('Delaware', 2);
insert into state (name, country_id) values ('Florida', 2);
insert into state (name, country_id) values ('Georgia', 2);
insert into state (name, country_id) values ('Hawaii', 2);
insert into state (name, country_id) values ('Idaho', 2);
insert into state (name, country_id) values ('Illinois', 2);
insert into state (name, country_id) values ('Indiana', 2);
insert into state (name, country_id) values ('Iowa', 2);
insert into state (name, country_id) values ('Kansas', 2);
insert into state (name, country_id) values ('Kentucky', 2);
insert into state (name, country_id) values ('Louisiana', 2);
insert into state (name, country_id) values ('Maine', 2);
insert into state (name, country_id) values ('Maryland', 2);
insert into state (name, country_id) values ('Massachusetts', 2);
insert into state (name, country_id) values ('Michigan', 2);
insert into state (name, country_id) values ('Minnesota', 2);
insert into state (name, country_id) values ('Mississippi', 2);
insert into state (name, country_id) values ('Missouri', 2);
insert into state (name, country_id) values ('Montana', 2);
insert into state (name, country_id) values ('Nebraska', 2);
insert into state (name, country_id) values ('Nevada', 2);
insert into state (name, country_id) values ('New Hampshire', 2);
insert into state (name, country_id) values ('New Jersey', 2);
insert into state (name, country_id) values ('New Mexico', 2);
insert into state (name, country_id) values ('New York', 2);
insert into state (name, country_id) values ('North Carolina', 2);
insert into state (name, country_id) values ('North Dakota', 2);
insert into state (name, country_id) values ('Ohio', 2);
insert into state (name, country_id) values ('Oklahoma', 2);
insert into state (name, country_id) values ('Oregon', 2);
insert into state (name, country_id) values ('Pennsylvania', 2);
insert into state (name, country_id) values ('Rhode Island', 2);
insert into state (name, country_id) values ('South Carolina', 2);
insert into state (name, country_id) values ('South Dakota', 2);
insert into state (name, country_id) values ('Tennessee', 2);
insert into state (name, country_id) values ('Texas', 2);
insert into state (name, country_id) values ('Utah', 2);
insert into state (name, country_id) values ('Vermont', 2);
insert into state (name, country_id) values ('Virginia', 2);
insert into state (name, country_id) values ('Washington', 2);
insert into state (name, country_id) values ('West Virginia', 2);
insert into state (name, country_id) values ('Wisconsin', 2);
insert into state (name, country_id) values ('Wyoming', 2);
